### ISSUE TITLE
Get tests running in GitHub actions

### ISSUE THREAD

**Issue by josephwoodward** [JosephWoodward/graphiql-dotnet#38]
GitHub action tests currently fail with the following error:

```
Run dotnet test src/graphiql.tests/ --configuration Development --nologo
##[warning]BaseTest.cs(40,30): warning CS0168: The variable 'e' is declared but never used [/home/runner/work/graphiql-dotnet/graphiql-dotnet/src/graphiql.tests/graphiql.tests.csproj]
Test run for /home/runner/work/graphiql-dotnet/graphiql-dotnet/src/graphiql.tests/bin/Development/netcoreapp3.1/graphiql.tests.dll(.NETCoreApp,Version=v3.1)
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {06adbfda-45e1-4c4d-8b95-3d842d41852f} may be persisted to storage in unencrypted form.
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Connection refused Connection refused
Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 44539
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Connection refused Connection refused
Connection refused Connection refused
[xUnit.net 00:00:07.45]     GraphiQl.tests.GraphQlTests.CanQueryGraphQl [FAIL]
  X GraphiQl.tests.GraphQlTests.CanQueryGraphQl [1ms]
  Error Message:
   OpenQA.Selenium.WebDriverException : unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  Stack Trace:
     at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at GraphiQl.tests.BaseTest..ctor(Boolean runHeadless) in /home/runner/work/graphiql-dotnet/graphiql-dotnet/src/graphiql.tests/BaseTest.cs:line 31
   at GraphiQl.tests.GraphQlTests..ctor(HostFixture fixture) in /home/runner/work/graphiql-dotnet/graphiql-dotnet/src/graphiql.tests/GraphQlTests.cs:line 14
```

**Comment by josephwoodward** [comment]
Fixed by using the Windows image.

**Comment by enochadeoluwa** [comment]
Hi Joseph,

Please can you provide more info on how you fixed this?
